kayak/fireant

fireant/slicer/managers.py
fireant/slicer/queries.py
fireant/slicer/references.py
fireant/slicer/schemas.py
fireant/slicer/transformers/highcharts.py
fireant/tests/slicer/test_queries.py
fireant/tests/slicer/test_slicer_api.py
fireant/tests/slicer/transformers/base.py
fireant/tests/slicer/transformers/test_highcharts.py
setup.py

Fixed end-to-end references for line charts, now all the bugs should be eliminated.
This was a bit more complex than I had originally planned, however it can probably be simplified in the future.  The data frame builds a wrapper query that selects from the original query and joins all of the reference queries.

Fixing references for Highcharts line charts

---

fireant/slicer/transformers/datatables.py
fireant/tests/slicer/transformers/test_datatables.py
fireant/tests/slicer/transformers/test_highcharts.py

Fixed:
- Dates are now formatted correctly as ISO strings
- Reference labels are now formatted correctly.

Fixes for Data Tables transformer

---

fireant/slicer/queries.py
fireant/slicer/transformers/datatables.py
fireant/slicer/transformers/highcharts.py
fireant/tests/database/test_databases.py
fireant/tests/slicer/transformers/test_datatables.py
fireant/tests/slicer/transformers/test_highcharts.py

- Converted the column names to unicode
- Added test coverage for highcharts and datatables data point formatter functions
- Added test coverage for database.fetch_dataframe
- Fixed checks for np.nan to use np.isnan instead of value is np.nan

pandas.read_sql returns DF with binary string col names

---

docs/2_slicer.rst
fireant/slicer/__init__.py
fireant/slicer/operations.py
fireant/slicer/transformers/datatables.py
fireant/slicer/transformers/highcharts.py
fireant/tests/slicer/test_slicer_api.py

Fixed for Highcharts
Line Charts
- Fixed the yAxis for metrics
Bar Charts
- Fixed the yAxis (should always be 0)
- Fixed the labels to correctly replace None and NaN values with 'Totals'

Fixes for Rollup operation in highcharts

---

docs/2_slicer.rst
fireant/slicer/managers.py
fireant/slicer/schemas.py
fireant/slicer/transformers/datatables.py
fireant/slicer/transformers/highcharts.py
fireant/slicer/transformers/notebook.py
fireant/tests/dashboards/test_dashboard_api.py
fireant/tests/slicer/test_slicer_api.py
fireant/tests/slicer/transformers/base.py
fireant/tests/slicer/transformers/test_datatables.py
fireant/tests/slicer/transformers/test_highcharts.py

Renamed  label_field and label_options in the dimension classes to avoid confusing with the label which is the display value for the dimension or metric as opposed the display values for the query results

Renamed label_field and label_options

---

fireant/dashboards/managers.py
fireant/slicer/managers.py
fireant/slicer/transformers/highcharts.py
fireant/tests/dashboards/test_dashboard_api.py

Fix for widget group that corrects the resulting data frame so that the labels are applied in the correct order.

Widgetgroup labels fix

---

fireant/slicer/transformers/datatables.py
fireant/tests/slicer/transformers/test_datatables.py

Fixes #56 Setting the display value as the default column value for the data tables transformer

Set display as the default render value in the datatables.js transformer

---

fireant/slicer/schemas.py

Fixed the schemas function for unique dimension to work when there is no display value set

Unique Dimension with no display value - Queries for dimension key

---

fireant/__init__.py
fireant/dashboards/managers.py
fireant/tests/dashboards/test_dashboard_api.py

Fixed the widget manager render function to pass a data frame to the transformer with the correct columns index

Reference columns

---

fireant/slicer/managers.py
fireant/slicer/transformers/highcharts.py
fireant/tests/slicer/test_managers.py
fireant/tests/slicer/test_operations.py
fireant/tests/slicer/test_slicer_api.py
fireant/utils.py

Changed transformer APIs to accept metrics as a list of list of metric keys to express which axis each metric should go on.  Does not break backwards compatibility since a list of metric keys will still work and render each metric on its own axis which is the same as the previous behavior.

Multi-axis metrics

---

fireant/slicer/transformers/datatables.py
fireant/tests/slicer/transformers/test_datatables.py

This pull request fixes sorting issues when using Fireant's datatables JSON. Now, columns with prefix/suffix can be sorted, even if they contain null values.
If there is a null value, the prefix/suffix is also now not shown, as before for example 'None%' was shown.
This should solve issue https://github.com/kayak/fireant/issues/80

Fixed datatables column sorting

---

fireant/dashboards/managers.py
fireant/slicer/operations.py
fireant/tests/dashboards/test_dashboard_api.py

Added temporary fix that stops operations from being left out of the output when you use the widget group manager. This can be removed when we refactor the Fireant API.

Added fix for operations not appearing when using widget groups

---

fireant/slicer/managers.py
fireant/slicer/queries.py
fireant/slicer/references.py
fireant/tests/slicer/test_queries.py
fireant/tests/slicer/test_slicer_api.py
requirements.txt
setup.py

Fixes #91 Refactored references to no longer require that the reference dimension is selected.

Refactored References to not require a selected dimension

---

fireant/slicer/managers.py
fireant/slicer/transformers/highcharts.py
fireant/tests/slicer/test_managers.py
fireant/tests/slicer/test_operations.py

Fixes #90 changed the slicer manager to remove extra columns used in operations from the data frame before transforming.  This prevents any exceptions in the transformers caused by trying to render series from columns in the data frame.

Remove unused columns from query result data frame

---

README.rst
docs/1_setup.rst
fireant/database/database.py
fireant/database/vertica.py
fireant/slicer/schemas.py
fireant/slicer/transformers/highcharts.py
fireant/tests/database/mock_database.py
fireant/tests/database/test_databases.py
fireant/tests/database/test_vertica.py
fireant/tests/slicer/test_queries.py
fireant/tests/slicer/test_slicer_api.py
fireant/tests/slicer/transformers/test_highcharts.py

This also makes Bar and Column charts use a datetime type for an axis when the axis data is a DatetimeIndex, therefore looking more consistent with how the Line chart format dates.

Fix rounding issue with datetime intervals for dimensions

---

fireant/slicer/transformers/datatables.py
fireant/tests/slicer/transformers/test_datatables.py

This address only the datatables case, since HighChart does not allow to change the thousand separator on a chart basis. That can be done on the client side though by setting the lang object with the global setOptions function (i.e. http://api.highcharts.com/highcharts/lang).

Add thousands punctuation to numbers

---

fireant/slicer/schemas.py
fireant/tests/slicer/test_slicer_api.py

Now we use IW for week (ISO week - weeks are Monday through to Sunday) and year to use Y (so years start on Jan 1st)
Further information: https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Date-Time/TRUNCDateTime.htm

Changed Vertica date trunc intervals for week and year

---

fireant/slicer/managers.py
fireant/slicer/queries.py
fireant/tests/slicer/test_queries.py
requirements.txt

- Fixed issues with how the pypika query was constructed with roll up
- Changed the default label value for slicer components to be the key (instead of formatting the key value)
- Upgraded to pypika 0.3.0

Fixes #129 Upgraded to latest pypika and fixed some bugs

---

.coveragerc
.travis.yml
README.rst
docs/1_setup.rst
docs/2_slicer.rst
fireant/database/__init__.py
fireant/database/database.py
fireant/database/mysql.py
fireant/database/vertica.py
fireant/slicer/managers.py
fireant/slicer/queries.py
fireant/slicer/schemas.py
fireant/tests/database/mock_database.py
fireant/tests/database/test_mysql.py
fireant/tests/database/test_vertica.py
fireant/tests/slicer/test_queries.py
requirements.txt
scripts/mysql_functions.sql
setup.py
tox.ini

- Added MySQL database class.
- Deprecated the old Vertica class with a warning, and added new VerticaDatabase class to match the new naming standard.
- Fixed a number of errors in the documentation and updated the docs with information about the new MySQLDatabase class.
- Changed PyPika to install the latest patch version.

Added MySQL support to FireAnt

---

fireant/slicer/transformers/highcharts.py
fireant/tests/mock_dataframes.py
fireant/tests/slicer/transformers/test_highcharts.py

This PR removes bugs in the display of metric labels when a boolean dimension is used.
- A boolean False is now displayed as '<metric> (False)' (before it was just '<metric>')
- An empty string or a None is now displayed as '<metric> (Null)' (before it was just '<metric>')

Metric labels for Boolean dimensions

---

fireant/slicer/transformers/highcharts.py

Stops tooltips from being truncated in highcharts, which was causing confusion to end-users.

Fix label formatting

---

fireant/__init__.py
fireant/database/mysql.py
fireant/database/vertica.py
fireant/slicer/queries.py
fireant/tests/slicer/test_queries.py

The YoY values were not matching correctly. This was because the date truncation was moving the dates to the first day of the ISO year when using the week interval. Therefore, in the reference query left join, the dates were different and nulls were appearing in the YoY column.
To fix this, in the reference query builder, if the reference is YoY and the week interval is specified, I add a year to the date, truncate it (so the dates match) and then remove a year so that the dates are still for a year before.
This was fixed to the spec defined by Ben Young.

Fix bug when YoY reference is used with week dimension interval

---

fireant/slicer/queries.py
fireant/tests/slicer/test_queries.py

The previous pagination implementation had a bug with the 'order by' clause ordering by the aggregation instead of the alias (this broke when we used nested queries). This small PR fixes that bug.

Fixed bug in pagination query by ordering by alias instead of the aggregation

---

fireant/slicer/queries.py
fireant/tests/slicer/test_queries.py
requirements.txt

This depends on a pypika PR https://github.com/kayak/pypika/pull/88/files
I've upgraded to the latest pypika version and adapted all of the queries in the unit test cases. Now group by and order by clauses will use the field aliases.

Upgraded pypika to 0.9.4 and adapted the queries in the tests

---

fireant/formats.py
fireant/slicer/operations.py
fireant/slicer/queries/builder.py
fireant/slicer/queries/database.py
fireant/slicer/queries/makers.py
fireant/slicer/queries/references.py
fireant/slicer/references.py
fireant/slicer/widgets/datatables.py
fireant/slicer/widgets/helpers.py
fireant/slicer/widgets/highcharts.py
fireant/slicer/widgets/pandas.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/queries/test_builder.py
fireant/tests/slicer/queries/test_database.py
fireant/tests/slicer/queries/test_dimension_choices.py
fireant/tests/slicer/test_operations.py
fireant/tests/slicer/widgets/test_csv.py
fireant/tests/slicer/widgets/test_datatables.py
fireant/tests/slicer/widgets/test_pandas.py
fireant/utils.py
requirements.txt
setup.py

Prepended a `$` character to all aliases to avoid collisions with column names

Fixes for the generated aliases

---

fireant/slicer/widgets/datatables.py
fireant/slicer/widgets/helpers.py
fireant/tests/slicer/widgets/test_datatables.py

Data tables would break any time a third dimension was added for two bugs
- The order of the dimensions did not match in the column definition and the data 
- A column definition was created for every combination of dimension values instead of just the ones in the data frame.

Fix col index tables

---

fireant/formats.py
fireant/slicer/dimensions.py
fireant/tests/slicer/widgets/test_pandas.py

If a metric was set to use precision 0, then an inf or nan result in the data frame would cause the transformer to raise an unhandled exception

Fixed the metric format function to correctly handle for inf and nan

---

fireant/slicer/queries/database.py

Fixed an issue using int values in data tables with pivot=true when there are NaNs in the data frame, then int gets converted to a float and that breaks the column definitions

Fixed Integer type dimensions on pivoted data tables

---

fireant/formats.py
fireant/slicer/base.py
fireant/slicer/filters.py
fireant/slicer/queries/database.py
fireant/slicer/widgets/__init__.py
fireant/slicer/widgets/base.py
fireant/slicer/widgets/csv.py
fireant/slicer/widgets/helpers.py
fireant/slicer/widgets/highcharts.py
fireant/slicer/widgets/pandas.py
fireant/slicer/widgets/reacttable.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/queries/test_database.py
fireant/tests/slicer/widgets/test_csv.py
fireant/tests/slicer/widgets/test_pandas.py
fireant/tests/slicer/widgets/test_reacttable.py
fireant/utils.py

Added a react-table transformer and changed pivot behavior of the Pandas and CSV transformers to pivot any dimension and to transpose the data frame.
These transformers accept two arguments: `pivot: List<Dimension>` and `transpose: bool` 
With pivoted dimensions, the tables will render dimension values across columns instead of rows. When transpose is true, the columns and rows will be swapped.

React-Table transformer

---

fireant/slicer/widgets/pandas.py
fireant/tests/slicer/widgets/test_pandas.py

Fixed a case where an empty sort array passed to the fireant transformers would raise an unhandled exception.

Added handle for empty sort array in pandas transformer

---

fireant/slicer/widgets/pandas.py
fireant/slicer/widgets/reacttable.py

Fixed react table transformer to sort with NaN values in the column by moving the fillna part after the sort

Fix ReactTable sorting with NaNs

---

fireant/slicer/widgets/pandas.py
fireant/tests/slicer/widgets/test_pandas.py

Changed the behavior of the pandas transfomer's sorting to ignore invalid indices

Handle invalid column idx in sort

---

fireant/slicer/widgets/pandas.py

Fixed an issue where a pivoted data frame would be filled with str values that in turn would lead to the sort breaking due to mixed data types in the sorted columns.

Fix fillna in pandas sortdataframe

---

fireant/slicer/widgets/pandas.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/widgets/test_pandas.py

Fixed another issue related to sorting data frames in the pandas transformer when there are no dimensions

Fixed sorting data frames with no dimensions

---

.travis.yml
fireant/slicer/base.py
fireant/slicer/dimensions.py
fireant/slicer/queries/makers.py
fireant/slicer/widgets/chart_base.py
fireant/slicer/widgets/highcharts.py
fireant/slicer/widgets/matplotlib.py
fireant/slicer/widgets/pandas.py
fireant/tests/slicer/widgets/test_matplotlib.py

Added a matplotlib widget.
The tests are a bit bare because I'm not sure how to evaluate the matplotlib objects. Will come back to that later.

Matplotlib widget

---

fireant/database/mysql.py
fireant/tests/database/test_mysql.py

For all drivers aside from pymysql, using a context manager like `with db.connect() as connection` returned a connection object. This was then passed to pandas which retrieved the cursor, executed the query and closed the cursor.
Pymysql's connection object returns a cursor object when used in a context manager. This PR adds a class which overrides the pymysql connection object to ensure that the connection object is returned on __enter__ and closed on __exit__ (which was not happening on the pymysql version). Note: This class could have been nested in the connect method, but that would make it hard to test, so I extracted it into a separate method.

Fixed mysql connection

---

fireant/slicer/dimensions.py
fireant/slicer/widgets/reacttable.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/widgets/test_reacttable.py
requirements.txt

Added support for hyperlink templates in dimensions which work with the reacttable widget

Support for Hyperlink Templates on Dimensions

---

fireant/slicer/widgets/helpers.py

Fixed a bug that raise an exception when a non-string type value for display definitions was used

Fixed non-string type display defintiions  with React Table

---

fireant/slicer/widgets/highcharts.py

Fixed the highcharts widget to sort the series data frame to force the x-axis dimension to always be ordered

Fixed sorting of chart widgets with one dimension active

---

fireant/slicer/queries/builder.py
fireant/slicer/queries/makers.py
fireant/tests/slicer/queries/test_build_orderbys.py
fireant/utils.py

Added a select statement for metrics included in the order by that are not selected as metrics.

Fixed queries ordered by a metric not selected in a widget

---

fireant/formats.py
fireant/slicer/queries/builder.py
fireant/slicer/queries/database.py
fireant/slicer/queries/makers.py
fireant/slicer/widgets/datatables.py
fireant/slicer/widgets/helpers.py
fireant/slicer/widgets/highcharts.py
fireant/slicer/widgets/reacttable.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/queries/test_build_dimensions.py
fireant/tests/slicer/queries/test_database.py
fireant/tests/slicer/widgets/test_highcharts.py
fireant/tests/slicer/widgets/test_reacttable.py
fireant/utils.py

Changed the handling of totals in the pandas dataframes used to store the query result sets to use marker values instead of trying to fill the values. This is because dimension values can be null, so the NaN and NaT types are reserved for that, and putting different data types in a pandas index changes the dtype to O, which prevents us from keying off of the dtype for transformers.

Improvement on how totals for dimensions are marked in pandas index

---

fireant/slicer/operations.py
fireant/slicer/queries/execution.py
fireant/tests/slicer/mocks.py
fireant/tests/slicer/test_execution.py
requirements.txt

- Fixed a bug in how the data frames are reduced after executing multiple queries so that the totals will be properly marked
- Fixed a bug in how share metrics are calculated when there are 3 or more dimensions active
- Added test cases to cover the data frame reduction step during the query execution

Share Metrics bug fixes

---

fireant/slicer/totals.py

fixed scrub totals to not rely in numpy's elementwise. This was returning a single bool instead of an array in some cases such as when there were nans in the data frame index.

Fixed scrub totals to to work with nans in index

---

fireant/slicer/widgets/highcharts.py
fireant/tests/slicer/widgets/test_highcharts.py
requirements.txt

Fixed a bug where missing series on categorical charts like bar and column would cause the existing data points to be put in the wrong category

Fixed highcharts category labels with missing series

---

fireant/slicer/widgets/helpers.py

Make sure that the dimension values are always an Iterable before calculating the number of used dimensions. Fix for #224

Convert dimension values to an Iterable

---

fireant/dataset/intervals.py
fireant/dataset/references.py
fireant/queries/builder.py
fireant/queries/field_helper.py
fireant/queries/finders.py
fireant/queries/reference_helper.py
fireant/queries/sql_transformer.py
fireant/queries/totals_helper.py
fireant/tests/queries/test_build_dimensions.py
fireant/tests/queries/test_build_references.py

Fixed references to align on the weekday when a date dimension is selected and uses an interval that is weekly or smaller. Also removed the special case for YoY references on weekly intervals so the fix for leap years is generalized and so that the YoY reference aligns correctly.

Fixed references to align to weekday

---

fireant/queries/reference_helper.py
fireant/tests/queries/test_build_references.py

Fixed references queries to correctly adapt the dimension and filters applied to the dimension when the dimension is wrapped with Rollup

Reference queries with Rollup on reference dimension 

---

fireant/tests/widgets/test_reacttable.py
fireant/widgets/pandas.py

Fixed an issue where when more that two dimensions are used, the first dimension is pivoted, and there is some column sorting applied to the table, the transformer would raise an exception

ReactTable transformation exception

---

fireant/formats.py
fireant/tests/test_formats.py

In react table it should be safe to use white spaces in accessors. 
For example `accessor = 'nospace.with space'` will be split up into `['nospace', 'with space']` which is used like normal keys starting from some base object `base_obj['nospace']['with space']`.
Details can be found in https://github.com/tannerlinsley/react-table/blob/master/src/utils.js#L202

Add whitespace as safe char

---

fireant/tests/database/test_base_database.py
fireant/tests/database/test_pickle.py

this ensures we can use concurrency middleware that pickles this object

added pickle tests for database object

---

setup.py

This is needed because of an issue with dependencies. A fix is being worked on: https://github.com/snowflakedb/snowflake-connector-python/issues/225

Temporary fix for snowflake dependency bug

---

fireant/tests/widgets/test_csv.py
fireant/widgets/pandas.py

Fixed the ordering of columns in csv to put the references directly after the metric columns

Order of columns in csv using references

---

fireant/queries/execution.py
fireant/tests/dataset/test_execution.py

in cases where there is data in the reference period and not in the current period, or vice versa, calculating references yielded NaNs. This PR fixes the calculation to fill missing values with zero.

Fixed calculation of ref with non-aligned indices

---

requirements-dev.txt
requirements-extras-snowflake.txt

I had to remove `cryptography==2.4.2` as requirements.txt already contains a pinned version for cryptography.

Pin urllib3 to 2.4.3 to fix the snowflake connector.

---

fireant/database/base.py
fireant/database/mysql.py
fireant/database/postgresql.py
fireant/database/snowflake.py
fireant/database/vertica.py
fireant/middleware/decorators.py
fireant/tests/database/test_base_database.py
fireant/tests/database/test_mysql.py
fireant/tests/database/test_postgresql.py
fireant/tests/database/test_snowflake.py
fireant/tests/database/test_vertica.py

- add optional connection argument to use connections for fetching data
- add execution method to write to database (with commit)
---
1. Example: Fetch using the same database connection
```python
db = Database()
with db.connect()  as connection:
db.fetch(query, connection=connection)
db.execute(query, connection=connection)
db.fetch(query)
```
---
Regarding thread-based concurrency middleware, it's worth mentioning that thread safety is __not__ guaranteed for sharing connections between threads by default:
- PEP 249: https://www.python.org/dev/peps/pep-0249/#threadsafety
- pymysql: https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/__init__.py#L43
- vertica-python: https://github.com/vertica/vertica-python/blob/master/vertica_python/__init__.py#L66

Add option to reuse database connections

---

setup.py

That spares us of maintaining the packages' list in setup.py file.

Use find_packages in setup.py file

---

fireant/dataset/data_blending.py
fireant/queries/builder/dataset_blender_query_builder/klass.py
fireant/tests/dataset/mocks.py
fireant/tests/queries/test_build_data_blending.py

Improves performance of data blender queryset by just returning primary dataset whenever only metrics of the primary dataset are used. Raises SlicerException whenever a secondary dataset
needs to be joined, due to a metric, but one of the requested dimensions is not mapped to its equivalent in the secondary dataset.

Improves performance of data blender queryset in some cases

---

fireant/dataset/data_blending.py
fireant/dataset/fields.py

This is necessary since it's validated when adding fields to DataSetBlender and often the definitions of those fields can be other fields

Added is_aggregate property to Field

---

fireant/database/base.py
fireant/middleware/__init__.py
fireant/middleware/concurrency.py
fireant/middleware/decorators.py
fireant/queries/execution.py
fireant/tests/database/test_base_database.py
fireant/tests/database/test_fetch.py
fireant/tests/dataset/test_execution.py
fireant/tests/test_middleware.py

I refactored the middlewares so that they actually work as proper middlewares in all cases. They will now always be applied to multiple queries instead of one.
I kept `fetch` and `fetch_dataframe` for backwards compatibility as `fetch_queries` and `fetch_dataframes` return lists of results.
I will add more tests after feedback as I'm not super happy about what these changes have caused to for instance the log_middlware implementation.

refactor middlewares to always work on multiple queries

---

fireant/dataset/data_blending.py
fireant/dataset/fields.py
fireant/dataset/filters.py
fireant/dataset/klass.py
fireant/dataset/modifiers.py
fireant/dataset/references.py
fireant/queries/builder/dataset_blender_query_builder.py
fireant/queries/builder/dataset_query_builder.py
fireant/queries/builder/query_builder.py
fireant/queries/finders.py
fireant/queries/reference_helper.py
fireant/queries/references.py
fireant/queries/sql_transformer.py
fireant/tests/dataset/mocks.py
fireant/tests/dataset/test_execution.py
fireant/tests/queries/test_build_data_blending.py
fireant/tests/queries/test_build_references.py
fireant/tests/queries/test_pagination.py
fireant/tests/widgets/test_highcharts.py
fireant/tests/widgets/test_reacttable.py
fireant/utils.py
fireant/widgets/base.py
fireant/widgets/chart_base.py

Fixed issues with deepcopy so that Fields are cached when a deepcopy is triggered via @immutable function in an instance of DataSet or Widget.
Fixed some issues where the ability to use "is" comparison on fields made things a lot cleaner.
Got rid of some field copying in some tests.

Fixed some deepcopy issues

---

fireant/dataset/references.py
fireant/queries/execution.py
fireant/queries/pandas_workaround.py
fireant/tests/dataset/test_execution.py
fireant/tests/dataset/test_pandas_workaround.py

fixed the subtraction of reference values to work around an issue with pandas where nans in the index lead to duplication

Fixed delta reference calculation to work when their are null values for a dimension

---

fireant/dataset/operations.py
fireant/tests/dataset/test_operations.py

Fixed cumulative operations to work when the query returns zero results

Fix cum operation no data

---

fireant/queries/references.py
fireant/tests/queries/test_build_dimensions.py
fireant/tests/queries/test_build_references.py

Inverted the logic on date range filters used with references so that that date math is applied to the filters' range parameters instead of the definition of the reference field.

Performance improvement for reference queries

---

fireant/database/base.py
fireant/middleware/concurrency.py
fireant/middleware/decorators.py
fireant/queries/execution.py
fireant/tests/database/test_fetch.py
fireant/tests/dataset/test_execution.py

This improvement made sense anyway as pandas' api for the parse_dates parameter on read_sql had evolved anyway.
This solved a problem we had with calculating totals on datablended dimensions.

Specify date dimensions when querying dataframes

---

fireant/queries/execution.py
fireant/tests/dataset/test_execution.py

A small improvement on yesterday's bugfix.

Fine tune the usage of pandas' parse_dates to not get NaT values

---

fireant/__init__.py
fireant/dataset/klass.py
fireant/dataset/modifiers.py
fireant/queries/finders.py
fireant/queries/sets.py
fireant/queries/sql_transformer.py
fireant/tests/queries/test_build_sets.py

This implements sets as a special filter modifier (i.e. ResultSet), just like OmitRollup. When a filter is wrapped with it set, it won't really be used as a filter in the SQL query generation. Instead it will be used to generate dimensions with a CASE statement as its definition, which will represent set membership given the filter conditional.
The newly created dimension (i.e. CASE dimension) will by default replace the original dimension, if the original dimension was selected in the query builder, otherwise it will be appended as the last dimension. This behaviour can be changed with the will_ignore_dimensions as False, which means that instead of replacing the original dimension in place, we simply insert the newly created dimension (i.e. CASE dimension) just before the original …

Add set filter modifier

---

fireant/dataset/filters.py
fireant/dataset/modifiers.py
fireant/queries/builder/dataset_blender_query_builder.py
fireant/queries/builder/dataset_query_builder.py
fireant/queries/builder/dimension_choices_query_builder.py
fireant/queries/builder/dimension_latest_query_builder.py
fireant/queries/builder/query_builder.py
fireant/queries/finders.py
fireant/queries/sets.py
fireant/queries/sql_transformer.py
fireant/tests/queries/test_build_data_blending.py
fireant/tests/queries/test_build_dimensions.py
fireant/tests/queries/test_build_references.py
fireant/tests/queries/test_build_sets.py
fireant/tests/queries/test_data_blending_integration.py
fireant/tests/queries/test_fetch_data.py
fireant/tests/test_fireant.py
requirements.txt

First commit is unrelated to my changes, but was necessary since pypika's version 0.37.6 changed how functions were formatted. Fyi aliases of nested args are no longer serialised. Therefore that broke some tests in fireant. The purpose of updating pypika was to fix an issue in which aggregate expressions, within case statements, wouldn't implement is_aggregate method correctly. And that impeded the correct use of sets using metrics.
Despite that, this PR adds a couple new features to the ResultSet filter modifier, such as the ability to break down the complement set. Some fixes, especially regarding the use of share dimensions/totals 
with sets were also addressed. I've added some documentation on the aforementioned features as well, given API is stabler now.

Improvements upon set filter modifier

---

fireant/queries/builder/dataset_query_builder.py
fireant/tests/queries/test_fetch_data.py
fireant/tests/widgets/test_csv.py
fireant/tests/widgets/test_highcharts.py
fireant/tests/widgets/test_matplotlib.py
fireant/tests/widgets/test_pandas.py
fireant/tests/widgets/test_reacttable.py
fireant/widgets/base.py
fireant/widgets/csv.py
fireant/widgets/highcharts.py
fireant/widgets/matplotlib.py
fireant/widgets/pandas.py
fireant/widgets/reacttable.py

Also removed dataset/slicer arg from Widget.transform method, given it's not used anywhere anymore. The only place it was used was in the highcharts widget, but that's no longer the case.

Change how highcharts widget references dimensions during x axis rendering

---

fireant/dataset/klass.py
fireant/queries/builder/dataset_query_builder.py
fireant/queries/builder/dimension_choices_query_builder.py
fireant/queries/sets.py
fireant/tests/queries/test_build_orderbys.py
fireant/tests/widgets/test_csv.py
fireant/tests/widgets/test_highcharts.py
fireant/tests/widgets/test_pandas.py
fireant/tests/widgets/test_reacttable.py
fireant/tests/widgets/test_widgets.py
fireant/widgets/highcharts.py
fireant/widgets/matplotlib.py
fireant/widgets/pandas.py
fireant/widgets/reacttable.py
requirements.txt

This PR adds a new kwarg called hide to pandas based widgets' (i.e. pandas, csv and reacttable) constructors. Dimensions referenced in this new kwarg will be removed within the scope of a widget's transform method. The reacttable widget has a special behaviour in regard to its hyperlink handling. A hidden dimension that another hyperlink may depend on is still taken into account, when serialising a non hidden dimension.
The apply_set_dimensions was changed to return a new list, given that could result in other methods being able to change QueryBuilder._dimensions via the return of its QueryBuilder.dimensions property. A very likely source of bugs for any new implementation that created artificial dimensions, such as the set feature.
Finally, the transform methods of widgets were made more …

Add hide arg to pandas based widgets

---

fireant/dataset/fields.py
fireant/queries/builder/dataset_blender_query_builder.py
fireant/queries/builder/query_builder.py
fireant/queries/sets.py
fireant/tests/dataset/mocks.py
fireant/tests/queries/test_build_data_blending.py
fireant/tests/queries/test_fetch_data.py

This fixes set feature for data blending. I've tested the use cases of using a dimension, a metric and a metric that is also being displayed. Please check tests to see how blending sql is being formatted.

Fix set feature for data blending

---

fireant/dataset/fields.py
fireant/tests/widgets/test_csv.py
fireant/tests/widgets/test_highcharts.py
fireant/tests/widgets/test_pandas.py
fireant/tests/widgets/test_reacttable.py
fireant/widgets/base.py
fireant/widgets/highcharts.py
fireant/widgets/matplotlib.py
fireant/widgets/pandas.py
fireant/widgets/reacttable.py

This adds a fetch_only optional kwarg to Field class' dunder init. When set to true a widget will ignore the presence of such field's alias when transforming dataframes, as part of the transform method. The use case is allowing hyperlink templates to be properly generated while avoiding the dependency field to be rendered as part of the widget. Fyi hyperlink templates are only supported in react table widget.

Add fetch only param to field

---

fireant/tests/widgets/test_highcharts.py
fireant/widgets/highcharts.py
requirements-dev.txt

The highcharts widget's transform method now returns multiple chart configs, when split by a dimension. One for each of the categories, as in distinct values, of the provided dimension. Otherwise it returns a single chart config. A smaller height is set when multiple charts exist. By default the height value is 400pxs, when its value is unset, but that is changed to 240pxs in the presence of multi charts.

Add split dimension feature to highchart widget

---

fireant/tests/widgets/test_highcharts.py
fireant/widgets/highcharts.py

Make tooltip.shared defaults to false, when only a single data point per series exists.  Since it looks clunky and often supersedes most of the chart.

Make tooltip.shared defaults to false in certain cases

---

fireant/queries/pagination.py
requirements.txt
setup.py

The change in behaviour regarding _apply_pagination and its bool mask was actually the result of a bug fix in Pandas. Previously boolean masks could not match the number of rows in length, but that wasn't consistent with other loc/iloc usages. So the Pandas team changed that on 0.25.0. See https://github.com/pandas-dev/pandas/issues/26658 or the indexing section on https://pandas.pydata.org/docs/whatsnew/v0.25.0.html for more info.

Bump pandas to v1.1.1

---

fireant/dataset/filters.py
fireant/queries/sets.py
fireant/tests/dataset/mocks.py
fireant/tests/queries/test_build_data_blending.py
fireant/tests/queries/test_build_sets.py

Pattern expressions, such as like/not like, were being replaced by a field, even though its left side of the operation was a LOWER function. Besides, I have found similar issues with IN, NOT IN and BETWEEN operations. Those were also fixed and tests were added to prevent regressions.

Fix set usage with pattern expressions for data blending

---

fireant/formats.py
fireant/tests/test_formats.py

In some cases when precision was not applied and use_raw_value=True, integers were losing a trailing zero.

Fix number formatting when using use_raw_value=True

---

fireant/formats.py
fireant/tests/test_formats.py

This ensures the raw values after the percentage to decimal conversion match the precision shown when not setting use_raw_value=True.

Ensure precision is retained after converting percentage to decimal

---

fireant/database/base.py
fireant/database/vertica.py
fireant/middleware/decorators.py
fireant/tests/database/test_vertica.py
fireant/tests/test_middleware.py

This allows for cancelling queries using the SIGINT signal instead of relying on a KeyboardInterrupt. The KeyboardInterupt has as disadvantage that the code stops running and goes into the exception handler.
By using a signal handler on SIGINT, the executing code keeps running. When the signal handler then cancels the query, the connection will remain open until it throws a cancellation exception. This way we don't have to provide our own cancel exception but can just rely on whatever Cancelled exception the database provides.
We also add the option to inject a waiting time after closing a connection.

Improve query cancelling with the option for delaying after exit.

---

fireant/dataset/fields.py

The ComparisonOperator values didn't match the method names on Field. This caused issues with __repr__. Renaming made most sense and now it has the same names as PyPika has for the Term class.

Let name of Field methods match comparison operator values and PyPika method names.

---

fireant/database/vertica.py
fireant/queries/execution.py
fireant/tests/database/test_vertica.py
fireant/tests/dataset/test_execution.py

Some database platforms ignore any query limits, so we strip the data that goes over the limit.
Also update the vertica timeout parameter name.

Strip rows over max row count from query result

---

requirements-extras-snowflake.txt
requirements.txt

The current version of the snowflake connector depends on a pinned version of urllib.

Update snowflake and pypika

---

fireant/exceptions.py
fireant/middleware/decorators.py
fireant/tests/test_middleware.py

We need to catch the KeyboardInterrupt and raise a different exception as a KeyboardInterrupt causes a Huey worker to end.
Only the snowflake connector has this issue as this connector attaches signal handlers itself to detect for cancellation.
We could make this behaviour database specific in the future, but I think for now this is fine.

Snowflake raises KeyboardInterrupt on cancel

---

.coveragerc
.github/workflows/black.yml
.github/workflows/pythonpackage.yml
fireant/queries/builder/dataset_blender_query_builder.py
fireant/tests/dataset/mocks.py
fireant/tests/queries/test_build_data_blending.py
pyproject.toml
requirements-dev.txt
requirements.txt
tox.ini

Previously, the generic Query class was imported and used when constructing data blending queries. This change ensures that the correct query class is used if a database that is not compatible with the Query class is used e.g. MSSQL/MySQL.
I could also look at changing pypika so each query builder class has a reference to its relevant query class if that approach is deemed better.

Use DB-specific pypika class in datablending

---

fireant/tests/widgets/test_highcharts.py
fireant/widgets/highcharts.py

Using totals with highcharts's widget currently breaks, due to the totals label not being correctly mapped to the respective split dimension column's value. A test was added to cover that scenario.

Fix highcharts totals when using split dimensions

---

.github/workflows/pythonpackage.yml
fireant/tests/widgets/test_pandas.py
fireant/widgets/pandas.py
fireant/widgets/reacttable.py

* Ensure totals values are reformatted to a human-friendly name, as this had been missed before.
* Ensure set dimensions with custom labels can be transformed. This was causing issues because the set functionality manipulates the dimension label. Previously, the Pandas transformer converted the column names to use the label before pivoting, however, the set label override caused this to break. Now, columns and index names are only converted to the labels after the pivoting has occurred.

Pandas transformer fixes

---

.github/workflows/pythonpackage.yml
fireant/queries/builder/dataset_blender_query_builder.py
fireant/tests/queries/test_build_data_blending.py
fireant/tests/queries/test_build_sets.py

This fixes an underlying issue, in which dimensions/metrics in data blending query builder, were not properly cloned. As a result of that, subsequent sql method calls could produce the wrong output. The as_ calls in _get_sq_field_for_blender_field were the main culprit. Even one of the tests were actually producing the right output, when run in conjunction with other tests, but failed when run individually. That's all fixed now.

Fix the usage of set dimensions along with refs for data blending

---

.github/workflows/pythonpackage.yml
fireant/database/base.py
fireant/database/mysql.py
fireant/tests/database/test_mysql.py
requirements-extras-mysql.txt

I tested this out quite a bit and this seems to do for now. We'll probably have to implement a proper cancel for most databases if they don't implement a cancel operation.

Mysql connector update + setting up timeout and cancel

---

fireant/__init__.py
fireant/dataset/references.py
fireant/reference_helpers.py
fireant/tests/test_fireant.py
fireant/tests/widgets/test_base.py
fireant/tests/widgets/test_csv.py
fireant/tests/widgets/test_highcharts.py
fireant/tests/widgets/test_pandas.py
fireant/tests/widgets/test_reacttable.py
fireant/widgets/base.py
fireant/widgets/csv.py
fireant/widgets/highcharts.py
fireant/widgets/matplotlib.py
fireant/widgets/pandas.py
fireant/widgets/reacttable.py

That way we can hide dimensions/metrics/referenced metrics. That makes sense in a few cases, like when using hyperlink templates in ReactTable but not wanting to display dependencies, when using references but wanting to display it for just a subset of the metrics or the counterpart.
This PR also introduces, DaysOverDays, WeeksOverWeeks, MonthsOverMonths, QuartersOverQuarters, and YearsOverYears as ReferenceType builders, which accept a custom interval. The original DayOverDay and so on are now relying on those newly created ReferenceType builders.

Add hide kwarg to all widgets

---

fireant/dataset/references.py
fireant/tests/dataset/test_references.py

This makes makes custom interval references reflect the interval in the label/alias of the ReferenceType.

Fix issues in custom interval references

---

fireant/database/snowflake.py
fireant/tests/database/test_snowflake.py

The use of IW was probably carried over from the Vertica implementation, but it is invalid. More info can be found here: https://docs.snowflake.com/en/sql-reference/functions-date-time.html#label-supported-date-time-parts

Fix Snowflake database ISO week truncation

---

CHANGELOG.md
fireant/__init__.py
fireant/widgets/pandas.py
pyproject.toml
setup.cfg

Optimize it by getting rid of `reset_index` and `set_index` method calls when sorting

SEOD-1531. Fix dataframe sort with a pivot with the new pandas v2 API
