kayak/fireant

- fireant/slicer/transformers/datatables.py
- fireant/slicer/transformers/highcharts.py
Fixes for Highcharts transformer
- NaN is now filtered from results in Column and Bar Charts
- Integers will now be returned as integer instead of as float
Fixes for Data Tables transformer
- Fixed numpy type issues so results can be serialized as json
> Fixing issues #6  and 7

- fireant/slicer/transformers/datatables.py
Fixes #23 references were inadvertently expected in column-index-tables even though none were set in the request.
> Fixed a bug where references were expected in column-index-tables

- fireant/settings.py
- fireant/slicer/transformers/highcharts.py
- fireant/tests/slicer/transformers/test_highcharts.py
Fixes #17 Added color settings for highcharts using the themes provided by highcharts
> Highcharts Color themes

- fireant/slicer/filters.py
- fireant/tests/slicer/test_filters.py
Added more test coverage for filters
> Added tests for filters

- docs/1_setup.rst
- fireant/dashboards/managers.py
- fireant/slicer/managers.py
- fireant/slicer/transformers/__init__.py
- fireant/slicer/transformers/base.py
- fireant/slicer/transformers/datatables.py
- fireant/slicer/transformers/highcharts.py
- fireant/slicer/transformers/notebook.py
- fireant/slicer/transformers/utils.py
- fireant/tests/slicer/test_manager.py
- fireant/tests/slicer/transformers/base.py
- fireant/tests/slicer/transformers/test_highcharts.py
- fireant/tests/slicer/transformers/test_notebook.py
- fireant/tests/slicer/transformers/test_utils.py
- setup.py
Fixes #25 added matplotlib and pandas transformers which work in jupyter notebook
> Added pandas and matplotlib transformers for use in Jupyter notebook

- fireant/database/vertica.py
- fireant/settings.py
- fireant/slicer/managers.py
- fireant/slicer/operations.py
- fireant/slicer/schemas.py
- fireant/slicer/transformers/base.py
- fireant/slicer/transformers/notebook.py
- fireant/slicer/transformers/utils.py
- fireant/tests/database/test_databases.py
- fireant/tests/database/test_vertica.py
- fireant/tests/slicer/test_operations.py
- fireant/tests/slicer/transformers/base.py
- fireant/tests/slicer/transformers/test_notebook.py
- setup.py
Filling in test coverage per this report https://coveralls.io/builds/7583385
> Test coverage

- fireant/slicer/managers.py
- fireant/slicer/transformers/notebooks.py
- fireant/slicer/transformers/utils.py
- fireant/tests/slicer/test_manager.py
- Fixed a bug where the metrics were not ordered correctly
- Fixed a bug where an exception was thrown due to pd.Index.set_levels being called
> Fixes for the Pandas/Matplotlib transformers

- docs/2_slicer.rst
- fireant/settings.py
- fireant/slicer/transformers/datatables.py
- fireant/slicer/transformers/highcharts.py
- fireant/tests/slicer/transformers/test_datatables.py
Fixes #29 Max columns setting for data tables
> Datatables maxcols

- fireant/slicer/postprocessors.py
- fireant/tests/slicer/test_managers.py
- fireant/tests/slicer/test_postprocessors.py
Fixes #39  Refactored the post_processing to streamline the individual operation code.
> Added L1 and L2 loss operations

- fireant/slicer/managers.py
- fireant/slicer/queries.py
- fireant/slicer/schemas.py
- fireant/tests/slicer/test_managers.py
- fireant/tests/slicer/test_queries.py
- fireant/tests/slicer/test_slicer_api.py
- setup.py
Adds a manager function to the slicer for querying dimension options for a given dimension.
> Dimension options

- docs/2_slicer.rst
- fireant/slicer/managers.py
- fireant/slicer/queries.py
- fireant/slicer/schemas.py
- fireant/tests/slicer/test_managers.py
- fireant/tests/slicer/test_queries.py
- fireant/tests/slicer/test_slicer_api.py
- setup.py
Fixes #53 Changed the query_schema code to join metrics and dimensions used in filters.  Changed the signature for filtering unique dimension display_field.
> Include all joins

- fireant/dashboards/managers.py
- fireant/slicer/references.py
- fireant/tests/dashboards/test_dashboard_api.py
- fireant/tests/slicer/test_slicer_api.py
- setup.py
Fixes #58 Fixed the WidgetGroup reference issues and also refactored references so that modifiers can be constructed with a reference instance
> WidgetGroup references

- fireant/slicer/managers.py
- fireant/slicer/queries.py
- fireant/slicer/references.py
- fireant/tests/slicer/test_queries.py
- fireant/tests/slicer/test_slicer_api.py
Changed references so that they can be externally extended.  Added interval and modifier attributes which the query builder uses to join a reference query and modifier the selected metrics.  Also added a DoD reference.
> Fixes #68 Reference Refactor

- fireant/slicer/managers.py
- fireant/tests/slicer/test_operations.py
Fixes #70  Fixed the getattr expression for operations so that it can handle a missing metric_key such as in the case of Totals
> Fix for missing metric_key attribute in Totals

- fireant/slicer/managers.py
- fireant/slicer/transformers/highcharts.py
Fixed a bug where the axis for each metric was incremented per metric and not per axis.  Was a simple typo of incrementing the the axis number within the wrong loop.
> Fix for displaying metrics on the multiple axes

- fireant/dashboards/managers.py
- fireant/slicer/transformers/datatables.py
Fix for issue https://github.com/kayak/fireant/issues/84
> Fixes for WidgetGroupManager and datatables transformer

- fireant/dashboards/managers.py
- fireant/slicer/managers.py
- fireant/slicer/queries.py
- fireant/tests/dashboards/test_dashboard_api.py
- fireant/tests/slicer/test_managers.py
Added a query_string method to the SlicerManager and the WidgetGroupManager, which returns the query string that will be used for retrieving the data when rendering widgets.
> Added a query_string method to the SlicerManager and the WidgetGroupManager

- fireant/dashboards/managers.py
- fireant/slicer/managers.py
- fireant/tests/dashboards/test_dashboard_api.py
- fireant/tests/slicer/transformers/test_highcharts.py
The prevalidation step was not performed in the WidgetGroupManager class.  Added calls to it and tests.
> Fixes #95 added widget prevalidation to WidgetGroup

- fireant/dashboards/__init__.py
- fireant/dashboards/schemas.py
- fireant/slicer/transformers/__init__.py
- fireant/slicer/transformers/highcharts.py
- fireant/tests/slicer/test_managers.py
- fireant/tests/slicer/transformers/test_highcharts.py
Added a highcharts transformer for area charts
> Added transformer for area charts

- fireant/slicer/schemas.py
The levels function for unique dimensions should return the display key, not the pypika term for it.
> Missing fix for unique totals

- fireant/slicer/filters.py
Need this for some antfarm test cases
> Added eq functions to filters to compare them

- fireant/slicer/__init__.py
- fireant/slicer/filters.py
- fireant/tests/slicer/test_filters.py
- requirements.txt
I added a BooleanFilter that accepts a value and adds a 'WHERE' or 'WHERE NOT' depending on whether the value is True or False.
> Added BooleanFilter

- README.rst
- docs/1_setup.rst
- docs/2_slicer.rst
- fireant/database/__init__.py
- fireant/database/database.py
- fireant/database/mysql.py
- fireant/database/postgresql.py
- fireant/database/redshift.py
- fireant/database/vertica.py
- fireant/slicer/managers.py
- fireant/slicer/queries.py
- fireant/slicer/references.py
- fireant/tests/database/test_mysql.py
- fireant/tests/database/test_postgresql.py
- fireant/tests/database/test_redshift.py
- fireant/tests/database/test_vertica.py
- fireant/tests/slicer/test_queries.py
- fireant/tests/slicer/test_slicer_api.py
- requirements.txt
- setup.py
* Added support for both platforms at once as they are extremely similar.
* Note: This PR is waiting on the PyPika PR here: https://github.com/kayak/pypika/pull/74 . Once that is merged, we can bump the PyPika version and then bump the minimum PyPika version in Fireant's requirements.txt and setup.py.
> Added support for Amazon Redshift and PostgreSQL support

- fireant/dashboards/managers.py
- fireant/dashboards/schemas.py
Added support to the widget group for default metric filters
> Added support for default metric filters to the widget group

- fireant/slicer/dimensions.py
- fireant/slicer/filters.py
- fireant/tests/slicer/queries/test_builder.py
- requirements.txt
- setup.py
Sorry for the large diff on the test file due to hitting the reformat.
Also - changed the 'wildcard' filter method on the UniqueDimension to 'like' to make it more natural to use.
> Added NOT LIKE support for WildcardFilters

- fireant/slicer/dimensions.py
- fireant/slicer/filters.py
- fireant/slicer/joins.py
- fireant/slicer/queries/finders.py
- fireant/tests/slicer/queries/test_builder.py
Added support for multiple patterns when using like and not_like filters
> Multipattern filters

- fireant/slicer/queries/builder.py
- fireant/tests/slicer/queries/test_dimension_choices.py
Added missing tests
Fixed format of dataframe key for display definition
> Fixed dimension choices query for unique dimensions with display definition

- fireant/slicer/queries/builder.py
- fireant/tests/slicer/queries/test_builder.py
Moved the limit/offset from being kwargs on the fetch method to being builder methods in the slicer query builder
> Added the limit/offset builder methods to slicer query builder 

- fireant/slicer/dimensions.py
- fireant/slicer/filters.py
- fireant/tests/slicer/queries/test_build_dimension_filters.py
- requirements.txt
- setup.py
Fixed the behavior of antipattern to negate the whole group of patterns together instead of individually
> AntiPattern filter SQL

- fireant/database/vertica.py
- fireant/tests/database/test_vertica.py
Per https://github.com/uber/vertica-python#utf-8-encoding-issues
> Fix unicode errors for vertica

- fireant/slicer/operations.py
- fireant/slicer/queries/builder.py
- fireant/slicer/widgets/reacttable.py
- fireant/tests/slicer/queries/test_build_render.py
- fireant/tests/slicer/test_operations.py
Forgot to handle NaN and Inf in the react table transformer
> Fix nans in reacttable

- fireant/slicer/operations.py
- fireant/slicer/queries/builder.py
- fireant/tests/slicer/queries/test_build_render.py
- fireant/tests/slicer/test_operations.py
Operations are not calculating values when references are applied
> Fixed operations to calculate for references

- fireant/slicer/widgets/reacttable.py
- fireant/tests/slicer/widgets/test_reacttable.py
Found some issues with display formatted, hard coded values from testing and some cases not covered, such as adding commas to numeric values.
> Fixed react table's display value formatting and added test cases

- fireant/formats.py
- fireant/slicer/widgets/reacttable.py
- fireant/tests/slicer/widgets/test_datatables.py
- fireant/tests/slicer/widgets/test_pandas.py
- fireant/tests/slicer/widgets/test_reacttable.py
- fireant/tests/test_formats.py
Reduced the amount of duplicated formatting code and fixed an issue where decimals values were not be displayed with comma separators
> Fixed reacttable to use the same formatting as datatablesjs

- fireant/slicer/widgets/pandas.py
- fireant/slicer/widgets/reacttable.py
- fireant/tests/slicer/widgets/test_pandas.py
Added support to the Pandas, React Table, and CSV transformers for sorting by column.
> Pandas sort columns

- fireant/slicer/queries/special_cases.py
- requirements.txt
Fixed the usage of timedelta where months or years were used as the interval.
> Fixed usage of timedelta with month/year intervals

- fireant/slicer/widgets/highcharts.py
- fireant/tests/slicer/widgets/test_highcharts.py
Changed the behavior of cycling through the colors to always iterate through colors so that each axis has the next color after the last color used in the last axis. Made the first series on each axis use the same line color as marker color, and markers are always the axis color.
> Fixed highcharts color repetition 

- fireant/slicer/queries/database.py
Fixed the calculation of reference values so that the calculation would work when the indices do not overlap
> Fixed reference reduce function

- fireant/slicer/queries/builder.py
- fireant/tests/slicer/queries/test_builder.py
Changed the logic for query hints to work with dialects that don't support it
> Fixed queries for dialects that don't use query hints

- fireant/slicer/widgets/highcharts.py
Fixed the sorting of chart series data sets so that only timeseries are sorted
> Fixed sort order for non-time-series charts

- fireant/slicer/widgets/highcharts.py
The fix involved disabling pandas from sorting the data frame groups when grouping the series together
> Fixed the highcharts widget to display series in the correct sort order

- fireant/slicer/widgets/highcharts.py
Fixed an issue where series data values was being filled with the string 'totals'
> Fixed issue filling NaNs on highcharts

- fireant/formats.py
Fixed it to return None instead of raising an exception checking the type
> Fixed a case where coerce type was being called with a None value.

- fireant/__init__.py
- fireant/slicer/queries/database.py
- fireant/slicer/queries/pagination.py
- fireant/slicer/widgets/highcharts.py
- fireant/tests/slicer/mocks.py
- fireant/tests/slicer/widgets/test_highcharts.py
Some cases of combinations of dimensions with rollup were not covered by the last change to the way rolled up dimensions are handled.
> Fix charts totals

- fireant/slicer/widgets/csv.py
- fireant/slicer/widgets/pandas.py
- requirements.txt
Added option for group pagination to csv, this way a query for a chart can be converted to a csv file with the same results. The group pagination flag determines whether or not data sets should be limited/offset by series or data points.
> Added pagination options to CSV widget

- fireant/database/__init__.py
- fireant/database/snowflake.py
- fireant/tests/database/test_snowflake.py
- requirements-dev.txt
- requirements.txt
- setup.py
Connector for snowflake. I haven't been able to test this code with an instance of snowflake yet so therefore the wip
> Added a snowflake db connector

- fireant/slicer/dimensions.py
- fireant/slicer/filters.py
- fireant/slicer/metrics.py
- fireant/slicer/queries/sql_transformer.py
- fireant/tests/slicer/query_builder/test_build_dimensions.py
- requirements.txt
Add option to apply filters to total dimensions individually instead of setting it once for all filters.
> Update how filters are applied to total dimensions

- docs/5_extending.rst
- fireant/slicer/dimensions.py
- fireant/slicer/filters.py
- fireant/slicer/metrics.py
- fireant/slicer/queries/builder.py
- fireant/slicer/queries/sql_transformer.py
- fireant/tests/slicer/query_builder/test_build_dimensions.py
- fireant/tests/slicer/query_builder/test_builder.py
- fireant/tests/test_formats.py
- fireant/utils.py
Forked from https://github.com/kayak/fireant/pull/222
> Added apply to total as a property each each filter in a slicer query

- fireant/queries/finders.py
- fireant/tests/widgets/test_csv.py
- fireant/tests/widgets/test_pandas.py
- fireant/tests/widgets/test_reacttable.py
- fireant/widgets/base.py
- fireant/widgets/csv.py
- fireant/widgets/highcharts.py
- fireant/widgets/matplotlib.py
- fireant/widgets/pandas.py
- fireant/widgets/reacttable.py
Fixed the CSV formatting to apply after pivoting, transposing, and sorting
> Fixed CSV formatting

- fireant/formats.py
Fix display formatting for Date type values
> Fix display formatting for Date type values

- fireant/formats.py
- fireant/tests/test_formats.py
Changed the format of Inf to be None
> Fixed the value used for Inf in highcharts

- fireant/database/snowflake.py
- requirements.txt
Use Snowflake query from Pypika in Snowflake database.
> Update snowflake client

- fireant/dataset/fields.py
- fireant/dataset/filters.py
- fireant/tests/queries/test_build_filters.py
- requirements.txt
Added a VoidFilter which can be used as a convenience for adding a filter that does not do anything
> Add VoidFilter

- fireant/tests/widgets/test_pandas.py
- fireant/widgets/csv.py
- fireant/widgets/pandas.py
Fixed the Pandas transformer to handle multiple mentrics, multiple dimensions, and a dimension unstacked.
> Pandas mutli-dim, multi-metric, pivot dim[0] transform 

- MANIFEST.in
Fixed the requirements file pattern to include all of the requirements files for extras
> fixed setup.py to include extras req files

- fireant/dataset/data_blending.py
- fireant/dataset/klass.py
- fireant/queries/__init__.py
- fireant/queries/builder/__init__.py
- fireant/queries/builder/dataset_blender_query_builder/klass.py
- fireant/widgets/chart_base.py
- fireant/widgets/reacttable.py
A couple changes that fix issues found when adopting the new dataset api (builder like) in dahsmore.
> Changes to data blending

- fireant/dataset/data_blending.py
- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/queries/builder/dataset_query_builder.py
- fireant/queries/builder/dimension_choices_query_builder.py
- fireant/queries/builder/query_builder.py
- fireant/queries/field_helper.py
- fireant/queries/pagination.py
- fireant/queries/references.py
- fireant/queries/special_cases.py
- fireant/queries/sql_transformer.py
- fireant/tests/queries/test_build_data_blending.py
Cleaned up ordering and fixed some bugs discovered while trying to implement applications for data blending
> More data blending related clean up

- fireant/dataset/fields.py
- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/queries/builder/query_builder.py
- fireant/tests/queries/test_build_data_blending.py
- fireant/tests/queries/test_data_blending_corner_cases.py
- fireant/utils.py
Fixed the dataset blender query builder to work with datasets that have conflicting aliases
> DataSetBlenderQueryBuilder bugfix

- fireant/queries/pagination.py
this definitely needs a test but I'll come back to it/
> fixed the filtering of orders in group pagination

- fireant/queries/builder/dimension_choices_query_builder.py
- fireant/tests/queries/test_dimension_choices.py
Add non-null to query for fetching dimension choices.
> Remove null values for dimension choice query

- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/tests/queries/test_build_data_blending.py
Per feedback, all dimensions should be usable with data blending, but the join should be based on mapped dimensions. Changed the behavior of data blending to allow all dimensions to be selected regardless of whether they are mapped
> Data blending dimensions

- fireant/dataset/data_blending.py
- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/queries/builder/dataset_query_builder.py
- fireant/queries/finders.py
- fireant/queries/special_cases.py
- fireant/queries/sql_transformer.py
- fireant/reference_helpers.py
- fireant/tests/queries/test_build_data_blending.py
- fireant/tests/queries/test_data_blending_integration.py
Look at the commits separately perhaps, especially since one commit is just black formatting.
> Datablending improvements for share, totals, references and multiple datasets.

- fireant/tests/queries/test_build_data_blending.py
- fireant/tests/queries/test_build_dimensions.py
- fireant/tests/queries/test_build_references.py
- fireant/tests/queries/test_data_blending_integration.py
- requirements.txt
Pypika updated the default option to use alias in functions to true (for nested functions) which is why some tests needed to be updated.
> Update pypika version and fix nested alias in tests

- README.rst
- fireant/dataset/data_blending.py
- fireant/dataset/fields.py
- fireant/dataset/filters.py
- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/queries/execution.py
- fireant/queries/finders.py
Added an is_wrapped property to make it easier to distinguish if a field has been wrapped during the data blending process.
* Also added extra typing and some additional context to the data blending comments.
> Fix latest data if data blending is being used

- fireant/database/base.py
- fireant/database/mssql.py
- fireant/dataset/data_blending.py
- fireant/dataset/fields.py
- fireant/dataset/modifiers.py
- fireant/queries/builder/dataset_blender_query_builder.py
- fireant/queries/sets.py
- fireant/queries/sql_transformer.py
- fireant/tests/queries/test_build_data_blending.py
- fireant/tests/queries/test_build_dimensions.py
- fireant/tests/queries/test_build_references.py
- fireant/tests/queries/test_build_sets.py
- fireant/tests/queries/test_data_blending_integration.py
- fireant/utils.py
- fireant/widgets/reacttable.py
There's still an issue with sets that I'm trying to solve but it would be nice to get a review already.
> Blended query optimization

- fireant/tests/widgets/test_reacttable.py
- fireant/widgets/reacttable.py
The code comment in reacttable.py explains why this is useful to have
> Add path_accessor key to react table transformer

- fireant/queries/sets.py
- fireant/tests/queries/test_build_data_blending.py
- fireant/tests/queries/test_build_sets.py
In fact such an issue existed for any criterion dealing with and/or, for instance., which is the PatternCriterion case whenever more than one pattern is declared.
> Fix filter set when dealing with multiple pattern criterions
